name: Zephyr Build and Test

on: [push, pull_request]

jobs:
  build-test:
    runs-on:
      - ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Python version
        run: |
          python3 --version

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: libcsp-zephyr

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: libcsp-zephyr
          toolchains: arm-zephyr-eabi

      - name: Twister
        run: |
          west twister -v --integration -T libcsp-zephyr

      - name: Upload Twister reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: twister-reports
          path: |
            libcsp-zephyr/twister-out/twister.json
            libcsp-zephyr/twister-out/twister.xml
            libcsp-zephyr/twister-out/twister_report.xml

